-- Clear existing sample data and insert realistic telco agents
DELETE FROM public.agent_catalog;

-- Insert telco-specific agents with realistic descriptions
INSERT INTO public.agent_catalog (name, description, category, tier, provider, status, metrics, tags, documentation_url) VALUES
('Network Performance Monitor', 'Real-time monitoring of cell tower performance, signal strength analysis, and automated fault detection across our 5G/4G infrastructure. Provides predictive maintenance alerts and capacity planning insights for field operations teams.', 'Network Operations', 'standard', 'Network Engineering', 'available', '{"uptime": 99.97, "alert_accuracy": 94.2, "response_time": 0.3, "coverage_monitoring": 100}', ARRAY['network-monitoring', '5g', 'predictive-maintenance', 'alerts'], 'https://docs.internal.telco/network-monitor'),

('Customer Care Assistant', 'Handles tier-1 customer inquiries including billing questions, service activation requests, and technical troubleshooting. Integrates with our CRM and billing systems to provide instant account access and automated resolution for 80% of common issues.', 'Customer Operations', 'standard', 'Customer Experience', 'available', '{"resolution_rate": 82.5, "avg_handle_time": 3.2, "customer_satisfaction": 4.6, "escalation_rate": 12.8}', ARRAY['customer-service', 'billing', 'troubleshooting', 'crm-integration'], 'https://docs.internal.telco/customer-care'),

('Revenue Assurance Agent', 'Monitors billing accuracy, detects revenue leakage, and identifies fraudulent usage patterns across prepaid and postpaid accounts. Cross-references usage data with network events to ensure accurate charging and prevent billing discrepancies.', 'Revenue Management', 'enterprise', 'Finance Operations', 'available', '{"fraud_detection_rate": 96.8, "revenue_recovery": 2.4, "false_positive_rate": 0.8, "processing_speed": 15000}', ARRAY['fraud-detection', 'billing-validation', 'revenue-protection'], 'https://docs.internal.telco/revenue-assurance'),

('Field Service Optimizer', 'Optimizes technician scheduling and routing for installation, maintenance, and repair activities. Considers traffic patterns, technician skills, equipment availability, and customer preferences to maximize first-time fix rates and minimize travel time.', 'Field Operations', 'premium', 'Operations Engineering', 'available', '{"schedule_efficiency": 89.3, "first_time_fix": 87.1, "travel_optimization": 23.5, "customer_satisfaction": 4.4}', ARRAY['scheduling', 'routing', 'field-service', 'optimization'], 'https://docs.internal.telco/field-optimizer'),

('Spectrum Management AI', 'Analyzes spectrum utilization patterns, predicts interference scenarios, and recommends frequency allocation adjustments. Ensures optimal spectrum efficiency across our licensed bands while maintaining regulatory compliance.', 'RF Engineering', 'enterprise', 'Spectrum Planning', 'available', '{"spectrum_efficiency": 91.7, "interference_reduction": 34.2, "compliance_score": 100, "optimization_accuracy": 88.9}', ARRAY['spectrum-analysis', 'interference-detection', 'regulatory-compliance'], 'https://docs.internal.telco/spectrum-mgmt'),

('Churn Prediction Engine', 'Identifies customers at risk of cancellation by analyzing usage patterns, payment history, customer service interactions, and competitive market data. Triggers retention campaigns and provides personalized offers to reduce churn rates.', 'Customer Analytics', 'premium', 'Marketing Intelligence', 'available', '{"churn_prediction_accuracy": 87.3, "retention_uplift": 15.8, "campaign_effectiveness": 23.4, "model_precision": 84.6}', ARRAY['churn-prediction', 'retention', 'analytics', 'customer-behavior'], 'https://docs.internal.telco/churn-engine'),

('Network Capacity Planner', 'Forecasts network traffic growth, identifies congestion hotspots, and recommends infrastructure upgrades. Analyzes historical usage data, demographic trends, and special events to ensure network capacity meets demand.', 'Network Planning', 'premium', 'Network Strategy', 'available', '{"forecast_accuracy": 92.1, "capacity_utilization": 78.3, "upgrade_precision": 89.7, "cost_optimization": 18.9}', ARRAY['capacity-planning', 'traffic-forecasting', 'infrastructure', 'network-optimization'], 'https://docs.internal.telco/capacity-planner'),

('Regulatory Compliance Monitor', 'Tracks regulatory requirements across multiple jurisdictions, monitors compliance metrics, and generates automated reports for telecom authorities. Ensures adherence to quality of service standards, accessibility requirements, and data protection regulations.', 'Regulatory Affairs', 'standard', 'Legal & Compliance', 'available', '{"compliance_score": 98.4, "report_automation": 95.0, "violation_detection": 99.1, "response_time": 2.1}', ARRAY['regulatory-compliance', 'reporting', 'qos-monitoring', 'data-protection'], 'https://docs.internal.telco/compliance-monitor');